variables:
    PROJECT_NAME:
        value: "bouffe"
        description: "project name in /var/www/html/"

generate-html:
    stage: build
    tags:
        - docker
        - material-mkdocs
    script:
        - mkdocs build --clean
    artifacts:
        paths:
            - site/

clean-deploy:
    stage: deploy
    tags:
        - localhost
        - shell
    script:
        - rm -rf /var/www/html/$PROJECT_NAME
        - mkdir /var/www/html/$PROJECT_NAME
        - cp -r site/* /var/www/html/$PROJECT_NAME
    needs:
        - job: generate-html
          artifacts: true

